### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [Leviathan1995/Soo#5]
I would like to point out that identifiers like "[`__Lvm__lmachine__`](https://github.com/Leviathan1995/Soo/blob/2f3329c480b84f346d8c185db2378d05cc33100e/Lsy_Lvm/lvm/lvm_lmachine.h#L10)" and "[`__Soo__parse__`](https://github.com/Leviathan1995/Soo/blob/8c4256ba3af233fee650cb531adf54496b67e5e8/Lsy_Soo/soo/soo_parse.h#L9)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by Leviathan1995** [comment]
让我想想

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by Leviathan1995** [comment]
你问的是如何避免未定义行为？具体情景是什么？在我的编译器吗？
